version: '3.7'
services:
  api:
    ports:
      - '8002:8002'
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002
    environment:
      PYTHONPATH: .
      MATCHA_ENVIRONMENT: debug
    # depends_on:
    #   - "redis"
  worker:
    ports:
    - '8003:8003'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PYTHONPATH: .
    command: python app/worker.py
    # depends_on:
    #   - "redis"
