version: '3.7'
services:
  # redis:
  #   image: redislabs/redismod
  #   ports:
  #     - 6379:6379
    # command: redis-cli -h 0.0.0.0 -p 6379 flushall
  api:
    ports:
      - '8002:8002'
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002
    environment:
      PYTHONPATH: .
      MATCHA_ENVIRONMENT: DEBUG
    # depends_on:
    #   - "redis"
  worker:
    ports:
    - '8003:8003'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PYTHONPATH: .
      MATCHA_ENVIRONMENT: DEBUG
    command: python app/worker.py
    # depends_on:
    #   - "redis"
